### PR TITLE
Keep children in layout when spinner is loading. Tests updated

### PR DESCRIPTION
**Pull request by Jason-AM**

### CODE REVIEW

**Comment by tcbegley** [comment]
Addresses issue raised in #463

**Review by tcbegley — APPROVED** [review]
This looks good to me. Was there something else left to do?

**Comment by Jason-AM** [comment]
I think that was all the required work. Should be good to go.

**Comment by Jason-AM** [comment]
> This looks good to me. Was there something else left to do?

I think that

**Pull request merged**
