### PR TITLE
Contribute Julia package / v0.10.8 of DashBootstrapComponents.jl

### PR DESCRIPTION
**Pull request by rpkyle**
This pull requests proposes to add a Dash.jl version of `dash-bootstrap-components`, as originally requested in https://github.com/plotly/Dash.jl/issues/11.

I have not contributed a Gulp.js script here, but I did add `themes.jl` which aims to provide a theming interface analogous to that already available in Python and R. A simple sample application demonstrating the proposed syntax:

```julia
using Dash, DashHtmlComponents, DashBootstrapComponents

app = dash(external_stylesheets=[dbc_themes.BOOTSTRAP]);

app.layout = html_div() do
    dbc_alert(
        "Hello, Bootstrap!", className="m-5"
    )
end;

run_server(app);
```

@tcbegley This version fixes the issue noted previously with `DashBase`.

### CODE REVIEW

**Comment by tcbegley** [comment]
Hey @rpkyle 

Thanks for this, taking a look now (sorry for slowness, just very busy these days). Did you manually add the `include` for `themes.jl` to `DashBootstrapComponents.jl` or is there a way to get the component generator to pick it up? When I regenerate the components that line disappears.

**Comment by tcbegley** [comment]
Just opened plotly/dash#1453 to add support for nested component structures. This will make sure the Julia component generator populates `deps/` correctly.

**Comment by tcbegley** [comment]
My above PR was incorporated into Dash 1.19.0 meaning I can push ahead on this. Sorry for the delay! 

I incorporated your changes into #519 and will close this PR in favour of that one.

**Comment by rpkyle** [comment]
Thanks @tcbegley!

**Pull request closed without merging**
