### PR TITLE
Update migration-guide.md

### PR DESCRIPTION
**Pull request by 3tilley**
Hello,

I was caught by this during a migration, so thought I would improve the docs for the next person

### CODE REVIEW

**Comment by tcbegley** [comment]
Hey @3tilley

Thanks for the contribution! Could you explain what you mean by "Must be used in callbacks"?

**Comment by 3tilley** [comment]
Sorry that wasn't very clear. It might be that `.children` still works for setting the initial text, but is deprecated and `.label` is preferred in which case it's not a breaking change.

If you want to set the text in a Dash callback though, `Output("progress-id", "children")` will silently fail and render something odd. You have to update to `Output("progress-id", "label")` - which is why it was a breaking change for us

**Comment by tcbegley** [comment]
Oh interesting, and `children` renders text ok if it's the initial value? Happy to merge in any case.

**Comment by 3tilley** [comment]
From what I could see, yes

**Pull request merged**
