### PR TITLE
Example with collapsible sidebar and navbar

### PR DESCRIPTION
**Pull request by harisbal**
Thank you very much for this awesome library.
I would like to suggest including an example (for multi-page apps) where both a collapsible sidebar and a navbar are present in the layout. What I have in mind is something similar to what we see in many bootstrap templates nowadays such as [this](https://adminlte.io/themes/v3/).

In this PR I have created the barebones of the example but since I'm very weak at the css part I cannot make it look right.
image

Any help to finish this example would be much appreciated

### CODE REVIEW

**Comment by harisbal** [comment]
This is great news. Of course we should wait for the new functionality in Bootstrap 5.
Cheers!

**Comment by harisbal** [comment]
I'm trying to have a go with Offcanvas but I I'm not sure it will help us achieve what I have in mind since Offcanvas disappears completely from the view.
I can't figure out how to place a collapsible sidebar (with icons and a toggle button) alongside a navbar like
this

Happy to work on this if you need help but some help with the css would be much appreciated

**Comment by harisbal** [comment]
It is close but not exactly what I'm looking for. 
The main issues are two: 

1. Use of a toggle button instead of `onhover`
2. Resize the content of the page depending on the state of the sidebar (collapsed or not)

I understand that the solution is to mix the [responsive-collapsible-sidebar](https://github.com/facultyai/dash-bootstrap-components/tree/main/examples/python/templates/multi-page-apps/responsive-collapsible-sidebar) and [collapsible-sidebar-with-icons](https://github.com/facultyai/dash-bootstrap-components/tree/main/examples/python/templates/multi-page-apps/collapsible-sidebar-with-icons) but I haven't managed to make this work.

**Comment by tlallema** [comment]
hello, I would also be interested to do the same things as @harisbal 
Did you make any progress on this ?
Do you have any example ?
Thank you

**Pull request closed without merging**
