### PR TITLE
Kill date pickers

### PR DESCRIPTION
**Pull request by tcbegley**
This PR removes `DatePickerSingle` and `DatePickerRange` as suggested in #148. It appears to have reduced the bundle size by about two thirds (!) from ~750KB to ~250KB.

### CODE REVIEW

**Comment by tcbegley** [comment]
While looking into `ramda` imports as suggested [here](https://github.com/facultyai/dash-bootstrap-components/issues/60#issuecomment-472301899) I noticed that these two components were also the only places we were using `ramda` without targeted imports, so possibly a large chunk of the reduction we're getting is due to the blanket imports getting removed.

**Comment by pbugnion** [comment]
To help people use `DatePicker{Single,Range}` from dash-core-components, should we write an example in the documentation somewhere? The deprecation exception could then point to that?

**Comment by pbugnion** [comment]
Apart from that, this looks good.

**Comment by tcbegley** [comment]
> To help people use DatePicker{Single,Range} from dash-core-components, should we write an example in the documentation somewhere? The deprecation exception could then point to that?

We could just link to the [dash-core-components docs](https://dash.plot.ly/dash-core-components/datepickersingle)? I'm not sure that our own documentation would add much?

**Comment by ZeroCool2u** [comment]
@tcbegley @pbugnion Is there any documentation on how to apply the theme to the DateRangePicker components? I haven't had any luck so far.

**Comment by tcbegley** [comment]
hey @ZeroCool2u, you can try this https://github.com/tcbegley/dash-bootstrap-css

**Comment by ZeroCool2u** [comment]
@tcbegley Great, thank you!

**Pull request merged**
